### ISSUE TITLE
Whats is test_driver folder? 

### ISSUE THREAD

**Issue by adrianofreires** [omergamliel3/-GetX-NewsAPI#1]
Hey man! I'm studying TDD Reso Coder too and wanna implements the GetX instead Bloc, this repository will help me a lot! But what does the test_driver folder?

**Comment by omergamliel3** [comment]
Hi Adrian, test_driver folder contains integration test files using flutter_driver package

**Comment by adrianofreires** [comment]
> Hi Adrian, test_driver folder contains integration test files using flutter_driver package

Nice! But he teaches in same tutorial, or have another to learn integration test? Did you indicate me some link?

**Comment by omergamliel3** [comment]
No, reso coder does not teach integration tests in the same tutorial, although you can take a look at the flutter official docs - https://flutter.dev/docs/cookbook/testing/integration/introduction.
In addition, reso coder has a very good tutorial on integration tests - https://youtu.be/izajHHFSa8o

**Comment by adrianofreires** [comment]
Thanks a lot!
